### ISSUE TITLE
Apple pass is generated, but invalid

### ISSUE THREAD

**Issue by FluffyDiscord** [chiiya/laravel-passes#18]
I have the following test pass

```php
use Chiiya\Passes\Apple\Components\Image;
use Chiiya\Passes\Apple\Enumerators\ImageType;
use Chiiya\Passes\Apple\PassFactory;

$pass = new \Chiiya\Passes\Apple\Passes\GenericPass(
    description: '15% off purchases',
    organizationName: 'organization',
    passTypeIdentifier: 'pass.identifier,
    serialNumber: '1',
    teamIdentifier: 'organization id',
);

$pass
    ->addImage(new Image('logo.png', ImageType::ICON))
    ->addImage(new Image('logo.png', ImageType::ICON, 2))
;
$factory = new PassFactory();
$factory->setCertificate(__DIR__ . "/Certificates55.p12");
$factory->setPassword('password');
$factory->setWwdr(__DIR__ . "/aww.pem");
$factory->setOutput(__DIR__);
$file = $factory->create($pass, 'filename');
```

this creates the pass file successfully, but i am unable to use/import them in my app. If i use the example passes that Apple provides https://developer.apple.com/services-account/download?path=/iOS/Wallet_Support_Materials/WalletCompanionFiles.zip, my app loads it just fine. 

Am I missing something?

**Comment by FluffyDiscord** [comment]
Same goes for google passes, none are valid. Is this library not working correctly?

**Comment by chiiya** [comment]
It's working fine for us in production for both Google and Apple (albeit not for a GenericPass but a Coupon), are you sure everything is configured correctly? The WWDR is up to date?

**Comment by FluffyDiscord** [comment]
I apologize, I had exported wrong certificate from Apple (I had to import the apple certificate on my machine, then move it under me from system and then be able to export it correctly).

The android just had different issue that I was able to solve before than
