### ISSUE TITLE
spatie/data-transfer-object is unmaintained

### ISSUE THREAD

**Issue by binarious** [chiiya/laravel-passes#20]
`spatie/data-transfer-object` shouldn't be used since the package isn't maintained anymore. In the best case, no dependency should be used for this at all.

**Comment by binarious** [comment]
Wrong repository, sorry.

**Comment by binarious** [comment]
@chiiya Actually the links in https://github.com/chiiya/passes/issues/new/choose redirect to this repository. Doesn't seem to be correct.

**Comment by chiiya** [comment]
Hey, see also https://github.com/chiiya/laravel-passes/issues/13

It's not trivial to re-implement the validation that is currently done w/o the `spatie/data-transfer-object` dependency
